### ISSUE TITLE
Write styles in multiline block even it is a single style

### ISSUE THREAD

**Issue by farishkash** [YardPer/prj-rev-bwfs-dasmoto#1]
https://github.com/YardPer/prj-rev-bwfs-dasmoto/blob/b709e5b9245833e268a4797c5d71bbf5aa1f3c86/DasmotosArts/resources/style.css#L19-L21

It is so much easier to read when it is formatted like this, plus you are more likely to see a missing semicolon or syntax error.

```
#brushes {
  background-color: mediumspringgreen;
}
#frames {
  background-color: lightcoral;
}
#paint {
  background-color: skyblue;
}
```

**Comment by YardPer** [comment]
Understood. Thank you for your input.
